# Generated by Django 4.0.3 on 2022-07-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_subject', models.CharField(max_length=1000)),
                ('session_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
