# Generated by Django 4.0.3 on 2022-03-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_delete_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('document', models.FileField(upload_to='user_files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='document',
        ),
    ]
