# Generated by Django 4.0.3 on 2022-03-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
    ]
