# Generated by Django 4.0.3 on 2022-03-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
